torchrun \
    --standalone \
    --nproc_per_node=1 \
    --master_port=29500 \
    gvendi_phase1_training.py \
    --model_name "raghavlite/B3_Qwen2_2B" \
    --model_backbone "qwen2_vl" \
    --bf16 \
    --pooling eos \
    --normalize True \
    --temperature 0.02 \
    --dataset_name "TIGER-Lab/MMEB-train" \
    --subset_name "VOC2007" \
    --dataset_split "original" \
    --image_dir "./vlm2vec_train/MMEB-train" \
    --output_dir "training/Qwen2_gvendi_phase1" \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --kd_loss_type "gvendi_phase1" \
    --lr_scheduler_type cosine \
    --learning_rate 1e-5 \
    --num_train_epochs 1 \
    --bf16 \
    --save_total_limit 2 \
    --logging_steps 1 \
    --save_strategy "epoch" \
    --seed 42 \
    --weight_decay 0.01 \
    --warmup_ratio 0.03 \
    --image_resolution low \
    --num_last_layer 1